### ISSUE TITLE
Changes to dQuery

### ISSUE THREAD

**Issue by notshi** [OCHA-DAP/hdx-scraper-iati-viz#17]
Hello,

We've made some changes to dQuery. All the data is streamed so it shouldn't have problems with large datasets anymore.
As a side effect, there's been some changes to the dQuery urls.

For instance, you should add `from=xson` to
https://github.com/OCHA-DAP/hdx-scraper-iati-viz/blob/f426ff85faeb2455f69cd1c6ccd3867870e0f4bd/config/project_configuration.yml#L6

so the new url should be

```
http://d-portal.org/dquery?from=xson&form=xml&sql=%s
```

Do let us know if anything is amiss.

**Comment by mcarans** [comment]
@notshi Thank you! I have made the change to our script and also switched to use streaming downloads.

**Comment by notshi** [comment]
Great! Happy for this issue to be closed if you think all is working as intended.

**Comment by mcarans** [comment]
Closing
